version:                          "2"

services:
  server:
    build:                        docker/.
    ports:
      - "8080:80"
    volumes:
      - ".:/var/www/html"
  mysql:
    environment:
      MYSQL_DATABASE:             'blog'
      MYSQL_USER:                 'blog'
      MYSQL_PASSWORD:             'blog'
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - "dbblog:/var/lib/mysql"

volumes:
  dbblog:
