index:
  url:       /
  module:    front
  action :   index

blog:
  url:       /blog
  module:    front
  action:    blog

post_view:
  url:       /post-([0-9]+)
  module:    front
  action:    postView
  varsNames:
        - id

login:
  url:       /login
  module:    security
  action :   login

logout:
  url:       /logout
  module:    security
  action :   logout
